name: "Publish"

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v2

      - name: "Use latest Node LTS"
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
          cache: yarn

      - name: "Install dependencies"
        run: yarn install

      - name: "Publish to npm"
        id: npmPublish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: "Add version tag"
        if: steps.npmPublish.outputs.type != 'none'
        run: |
          git tag v${{ steps.npmPublish.outputs.version }}
          git push origin v${{ steps.npmPublish.outputs.version }}
